// src/app/Intro.tsx
import Image from 'next/image'

export default function Intro() {
  return (
    <section
      id="home"
      className="flex flex-col justify-center items-center text-primary-content"
    >
      <Image
        className="mt-10 bg-glass w-72 aspect-square rounded-full"
        src="/images/profile.webp"
        alt="ShrJamal Profile"
        width="288"
        height="288"
        priority
      />
      <h1 className="mt-4 text-4xl text-center text-primary-content">
        Jamal ASAHRAOUI
      </h1>
      <h2 className="text-lg font-thin ">Self-taught Full Stack Developer</h2>
    </section>
  )
}

// src/lib/sections/Intro.svelte
<section class="mt-10" id="home">
  <div class="flex flex-col justify-center ">
    <div class="text-center flex flex-col items-center">
      <span>Hello, I am </span>
      <h1 class="text-6xl my-2 w-80 text-center ">
        Jamal <span class="text-lg">Asahraoui</span>
      </h1>
      <h3 class="text-lg font-thin">
        Self-taught Full Stack Javascript Developer
      </h3>
    </div>
    <div class="flex my-10 justify-center">
      <div
        class="w-52 h-82 mx-2 flex items-end rounded-t-full rounded-b-2xl from-primary to-primary-content bg-gradient-to-b"
      >
        <img src="/profile.webp" target="_blank" alt="" />
      </div>
    </div>
  </div>
</section>
