// src/lib/sections/Contact.svelte
<section class="text-center" id="contact">
  <h2 class="text-2xl text-primary mb-2">Get in Touch</h2>

  <div class="flex justify-center items-center space-x-2">
    <a
      class="btn btn-circle bg-base-100"
      href="https://twitter.com/shrjamal"
      target="_blank"
    >
      <i class="text-blue-500 text-xl bx bxl-twitter" />
    </a>
    <a
      class="btn btn-circle bg-base-100  "
      href="https://www.linkedin.com/in/shrjamal"
      target="_blank"
    >
      <i class="text-blue-300 text-xl bx bxl-linkedin-square" />
    </a>
    <a
      class="btn btn-circle bg-base-100"
      href="https://github.com/shrjamal"
      target="_blank"
    >
      <i class="text-white text-xl bx bxl-github" />
    </a>
    <!-- Email -->
    <div class="bg-base-200 rounded-xl p-4">
      <div class="flex flex-col items-center">
        <h3 class="text-lg">
          <i class="bx bx-mail-send " /> Email
        </h3>
        <span>me@shrjamal.com</span>
        <a
          class="underline text-primary"
          href="mailto:me@shrjamal.com"
          target="_blank"
        >
          Write me <i class="bx bx-right-arrow-alt  underline" />
        </a>
      </div>
    </div>
    <!-- Telegram -->
    <a
      class="btn btn-circle bg-base-100"
      href="https://t.me/jamalshr"
      target="_blank"
    >
      <i class="text-blue-400 text-xl bx bxl-telegram" />
    </a>
    <a
      class="btn btn-circle bg-base-100"
      href="https://join.skype.com/invite/bOsjSN8qhcQh"
      target="_blank"
    >
      <i class="text-blue-400 text-xl bx bxl-skype" />
    </a>
    <a
      class="btn btn-circle bg-base-100  "
      href="tel:+923001234567"
      type="tel"
      target="_blank"
    >
      <i class="text-green-400 text-xl bx bxl-whatsapp" />
    </a>
  </div>
</section>

// src/components/Contact.tsx
import Link from 'next/link'
import { BiMailSend } from 'react-icons/bi'
import {
  BsGithub,
  BsLinkedin,
  BsSkype,
  BsTelegram,
  BsTwitter,
  BsWhatsapp,
} from 'react-icons/bs'

export default function Contact() {
  return (
    <section
      className="max-w-[30rem] mx-auto mt-4 grid sm:grid-cols-9 grid-color-3 gap-2 justify-center items-center"
      id="contact"
    >
      {contactInfo.map((it) =>
        it.name === 'Email' ? (
          <div
            key={it.name}
            className="bg-glass rounded-xl col-span-3 p-2 flex flex-col items-center"
          >
            <h3 className="text-lg flex items-center">
              <i className="mr-1 text-2xl"> {it.icon} </i>
              Email
            </h3>
            <span>{it.url}</span>
            <a
              className="underline text-slate-300 text-sm flex items-center"
              href={`mailto:${it.url}`}
              target="_blank"
              rel="noreferrer"
              title={it.name}
            >
              Write me {it.icon}
            </a>
          </div>
        ) : (
          <Link
            key={it.name}
            className="bg-glass btn btn-circle btn-outline hover:bg-black"
            href={it.url}
            target="_blank"
            rel="noreferrer"
            title={it.name}
          >
            <i className="text-3xl text-white"> {it.icon} </i>
          </Link>
        ),
      )}
    </section>
  )
}

const contactInfo = [
  {
    name: 'Github',
    url: 'https://github.com/shrjamal',
    icon: <BsGithub />,
  },
  {
    name: 'Twitter',
    url: 'https://twitter.com/shrjamal',
    icon: <BsTwitter />,
  },
  {
    name: 'Linkdin',
    url: 'https://www.linkedin.com/in/shrjamal',
    icon: <BsLinkedin />,
  },
  {
    name: 'Email',
    url: 'me@shrjamal.com',
    icon: <BiMailSend />,
  },
  {
    name: 'Telegram',
    url: 'https://t.me/jamalshr',
    icon: <BsTelegram />,
  },
  {
    name: 'Skype',
    url: 'https://join.skype.com/invite/bOsjSN8qhcQh',
    icon: <BsSkype />,
  },
  {
    name: 'Whatsapp',
    url: 'https://wa.me/2120700862543',
    icon: <BsWhatsapp />,
  },
]
