// src/routes/experience.svelte
<script>
  const experiences = [
    {
      description:
        "I'm Top Rated freelancer on Upwork, worked with more 20+ clients.",
      company: 'Upwork',
      img: '/upwork.webp',
      alt: 'Shrjamal Upwork Profile',
      link: 'https://www.upwork.com/freelancers/shrjamal',
      date: 'since 2022',
    },
    {
      description: "I'm Level 1 Seller in Fiverr",
      company: 'Fiverr',
      img: '/fiverr.webp',
      alt: 'Shrjamal Fiverr Profile',
      link: 'https://www.fiverr.com/jamalshr',
      date: 'since 2018',
    },
  ]
</script>

<section id="experience" class="flex flex-col px-4">
  <h2 class="text-2xl font-bold text-primary text-center">Experience</h2>

  <div class="flex flex-col">
    {#each experiences as item}
      <div class="card flex flex-row mt-4 bg-base-300 max-h-[20rem] w-full">
        <img class="w-40 w-48 mr-4" src={item.img} alt={item.alt} />
        <div class="flex flex-col pr-4 py-4 w-full">
          <h3 class="flex-1 ">{item.description}</h3>
          <div class="flex justify-between items-center">
            <p class="text-2xs">{item.date}</p>
            <a
              class="link link-primary text-right"
              href={item.link}
              target="_blank"
            >
              Hire Me
            </a>
          </div>
        </div>
      </div>
    {/each}
  </div>
</section>

// src/components/Experience.tsx
import Image from 'next/image'

export default function Experience() {
  return (
    <section id="experience" className="mt-8 flex flex-col items-center">
      <h2 className="gradient-text text-4xl ">Experience</h2>
      <div className="mt-4 grid sm:grid-cols-2 grid-cols-1 gap-4 ">
        {experiences.map((it) => (
          <a
            key={it.company}
            className="bg-glass w-80 flex flex-col rounded-xl p-2"
            href={it.link}
            target="_blank"
            rel="noreferrer"
          >
            <Image
              className="bg-white w-80 h-48 object-contain rounded-t-xl"
              width="160"
              height="120"
              src={it.img}
              alt={it.alt}
              loading="lazy"
            />
            <h3 className="mt-2 flex-1 ">{it.description}</h3>
          </a>
        ))}
      </div>
    </section>
  )
}

const experiences = [
  {
    description:
      'Top Rated freelancer on Upwork, worked with more 30+ clients. I have 100% positive reviews on Upwork.',
    company: 'Upwork',
    img: '/images/upwork.webp',
    alt: 'Shrjamal Upwork Profile',
    link: 'https://www.upwork.com/freelancers/shrjamal',
    date: 'since 2022',
  },
  {
    description: 'Level 1 Seller in Fiverr with 100% positive reviews.',
    company: 'Fiverr',
    img: '/images/fiverr.webp',
    alt: 'Shrjamal Fiverr Profile',
    link: 'https://www.fiverr.com/jamalshr',
    date: 'since 2018',
  },
]
